package sec2;
//UserException
public class UserException1 {

	public static void main(String[] args) {
		try {
			method1();
		} catch (RunException e) {
			e.printStackTrace();
		}
	}
	public static void method1() throws RunException{
		throw new RunException("사용자 예외");
	}

}
